version: '3'

services:
  web:
    image: sepulsa/alicantoapps:latest
    container_name: alicantoweb
    command: npm run start
    networks:
      - frontend
    ports:
      - 3001:3000
    environment:
      NODE_PORT: ${NODE_PORT}
      NODE_ENV: ${NODE_ENV}

networks:
  frontend:
    driver: bridge
