version: '3'

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
    depends_on:
      - web

  web:
    image: sepulsa/alicantodeps:latest
    command: npm run dev
    volumes:
      - .:/app
    networks:
      - frontend
    environment:
      NODE_PORT: ${NODE_PORT}
      NODE_ENV: ${NODE_ENV}

networks:
  frontend:
    driver: bridge
